site_name: FastClime
theme:
  name: material
plugins:
  - search
  - mkdocstrings

nav:
  - Home: docs/index.md
  - Architecture:
      - Modules Overview: docs/modules.md
      - M0 Storage-Hub: 'docs/auto/m0_storage.md'
      - M1 ETL-Ingest:  'docs/auto/m1_etl.md'
      - M2 Dynamic-Model: 'docs/auto/m2_dynamic.md'
      - M3 ML-Predict: 'docs/auto/m3_ml.md'
      - M4 Dashboard: 'docs/auto/m4_dashboard.md'
